

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.util.ArrayList;
/**
 * Servlet implementation class scorretraitement
 */
@WebServlet("/scorretraitement")
public class scorretraitement extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public scorretraitement() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		response.getWriter().append("Served at: ").append(request.getContextPath());
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
		HttpSession sesion = request.getSession();
		 
		int parametre =Integer.parseInt( request.getParameter("3-3"));
		int parametre00 =Integer.parseInt( request.getParameter("0-0"));
		int parametre01 =Integer.parseInt( request.getParameter("0-1"));
//		int parametre02 =Integer.parseInt( request.getParameter("0-2"));
//		int parametre03 =Integer.parseInt( request.getParameter("0-3"));
//		int parametre04 =Integer.parseInt( request.getParameter("0-4"));
//		int parametre05 =Integer.parseInt( request.getParameter("0-5"));
//		int parametre06 =Integer.parseInt( request.getParameter("0-6"));
//		int parametre07 =Integer.parseInt( request.getParameter("0-7"));
//		int parametre08 =Integer.parseInt( request.getParameter("0-8"));
//		int parametre09 =Integer.parseInt( request.getParameter("0-9"));
//		int parametre010 =Integer.parseInt( request.getParameter("0-10"));
//		int parametre10 =Integer.parseInt( request.getParameter("1-0"));
//		int parametre11 =Integer.parseInt( request.getParameter("1-1"));
//		int parametre12 =Integer.parseInt( request.getParameter("1-2"));
//		int parametre13 =Integer.parseInt( request.getParameter("1-3"));
//		int parametre14 =Integer.parseInt( request.getParameter("1-4"));
//		int parametre15 =Integer.parseInt( request.getParameter("1-5"));
//		int parametre16 =Integer.parseInt( request.getParameter("1-6"));
//		int parametre17 =Integer.parseInt( request.getParameter("1-7"));
//		int parametre18 =Integer.parseInt( request.getParameter("1-8"));
//		int parametre19 =Integer.parseInt( request.getParameter("1-9"));
//		int parametre110 =Integer.parseInt( request.getParameter("1-10"));
//		int parametre20 =Integer.parseInt( request.getParameter("2-0"));
//		int parametre21 =Integer.parseInt( request.getParameter("2-1"));
//		int parametre22 =Integer.parseInt( request.getParameter("2-2"));
//		int parametre23 =Integer.parseInt( request.getParameter("2-3"));
//		int parametre24 =Integer.parseInt( request.getParameter("2-4"));
//		int parametre25 =Integer.parseInt( request.getParameter("2-5"));
//		int parametre26 =Integer.parseInt( request.getParameter("2-6"));
//		int parametre27 =Integer.parseInt( request.getParameter("2-7"));
//		int parametre28 =Integer.parseInt( request.getParameter("2-8"));
//		int parametre29 =Integer.parseInt( request.getParameter("2-9"));
//		int parametre210 =Integer.parseInt( request.getParameter("2-10"));
//		int parametre30 =Integer.parseInt( request.getParameter("3-0"));
//		int parametre31 =Integer.parseInt( request.getParameter("3-1"));
//		int parametre32 =Integer.parseInt( request.getParameter("3-2"));
//		int parametre33 =Integer.parseInt( request.getParameter("3-3"));
//		int parametre34 =Integer.parseInt( request.getParameter("3-4"));
//		int parametre35 =Integer.parseInt( request.getParameter("3-5"));
//		int parametre36 =Integer.parseInt( request.getParameter("3-6"));
//		int parametre37 =Integer.parseInt( request.getParameter("3-7"));
//		int parametre38 =Integer.parseInt( request.getParameter("3-8"));
//		int parametre39 =Integer.parseInt( request.getParameter("3-9"));
//		int parametre310 =Integer.parseInt( request.getParameter("3-10"));
//		int parametre40 =Integer.parseInt( request.getParameter("4-0"));
//		int parametre41 =Integer.parseInt( request.getParameter("4-1"));
//		int parametre42 =Integer.parseInt( request.getParameter("4-2"));
//		int parametre43 =Integer.parseInt( request.getParameter("4-3"));
//		int parametre44 =Integer.parseInt( request.getParameter("4-4"));
//		int parametre45 =Integer.parseInt( request.getParameter("4-5"));
//		int parametre46 =Integer.parseInt( request.getParameter("4-6"));
//		int parametre47 =Integer.parseInt( request.getParameter("4-7"));
//		int parametre48 =Integer.parseInt( request.getParameter("4-8"));
//		int parametre49 =Integer.parseInt( request.getParameter("4-9"));
//		int parametre410 =Integer.parseInt( request.getParameter("4-10"));
//		int parametre50 =Integer.parseInt( request.getParameter("5-0"));
//		int parametre51 =Integer.parseInt( request.getParameter("5-1"));
//		int parametre52 =Integer.parseInt( request.getParameter("5-2"));
//		int parametre53 =Integer.parseInt( request.getParameter("5-3"));
//		int parametre54 =Integer.parseInt( request.getParameter("5-4"));
//		int parametre55 =Integer.parseInt( request.getParameter("5-5"));
//		int parametre56 =Integer.parseInt( request.getParameter("5-6"));
//		int parametre57 =Integer.parseInt( request.getParameter("5-7"));
//		int parametre58 =Integer.parseInt( request.getParameter("5-8"));
//		int parametre59 =Integer.parseInt( request.getParameter("5-9"));
//		int parametre510 =Integer.parseInt( request.getParameter("5-10"));
//		int parametre60 =Integer.parseInt( request.getParameter("6-0"));
//		int parametre61 =Integer.parseInt( request.getParameter("6-1"));
//		int parametre62 =Integer.parseInt( request.getParameter("6-2"));
//		int parametre63 =Integer.parseInt( request.getParameter("6-3"));
//		int parametre64 =Integer.parseInt( request.getParameter("6-4"));
//		int parametre65 =Integer.parseInt( request.getParameter("6-5"));
//		int parametre66 =Integer.parseInt( request.getParameter("6-6"));
//		int parametre67 =Integer.parseInt( request.getParameter("6-7"));
//		int parametre68 =Integer.parseInt( request.getParameter("6-8"));
//		int parametre69 =Integer.parseInt( request.getParameter("6-9"));
//		int parametre610 =Integer.parseInt( request.getParameter("6-10"));
//		int parametre70 =Integer.parseInt( request.getParameter("7-0"));
//		int parametre71 =Integer.parseInt( request.getParameter("7-1"));
//		int parametre72 =Integer.parseInt( request.getParameter("7-2"));
//		int parametre73 =Integer.parseInt( request.getParameter("7-3"));
//		int parametre74 =Integer.parseInt( request.getParameter("7-4"));
//		int parametre75 =Integer.parseInt( request.getParameter("7-5"));
//		int parametre76 =Integer.parseInt( request.getParameter("7-6"));
//		int parametre77 =Integer.parseInt( request.getParameter("7-7"));
//		int parametre78 =Integer.parseInt( request.getParameter("7-8"));
//		int parametre79 =Integer.parseInt( request.getParameter("7-9"));
//		int parametre710 =Integer.parseInt( request.getParameter("7-10"));
//		int parametre80 =Integer.parseInt( request.getParameter("8-0"));
//		int parametre81 =Integer.parseInt( request.getParameter("8-1"));
//		int parametre82 =Integer.parseInt( request.getParameter("8-2"));
//		int parametre83 =Integer.parseInt( request.getParameter("8-3"));
//		int parametre84 =Integer.parseInt( request.getParameter("8-4"));
//		int parametre85 =Integer.parseInt( request.getParameter("8-5"));
//		int parametre86 =Integer.parseInt( request.getParameter("8-6"));
//		int parametre87 =Integer.parseInt( request.getParameter("8-7"));
//		int parametre88 =Integer.parseInt( request.getParameter("8-8"));
//		int parametre89 =Integer.parseInt( request.getParameter("8-9"));
//		int parametre810 =Integer.parseInt( request.getParameter("8-10"));
//		int parametre90 =Integer.parseInt( request.getParameter("9-0"));
//		int parametre91 =Integer.parseInt( request.getParameter("9-1"));
//		int parametre92 =Integer.parseInt( request.getParameter("9-2"));
//		int parametre93 =Integer.parseInt( request.getParameter("9-3"));
//		int parametre94 =Integer.parseInt( request.getParameter("9-4"));
//		int parametre95 =Integer.parseInt( request.getParameter("9-5"));
//		int parametre96 =Integer.parseInt( request.getParameter("9-6"));
//		int parametre97 =Integer.parseInt( request.getParameter("9-7"));
//		int parametre98 =Integer.parseInt( request.getParameter("9-8"));
//		int parametre99 =Integer.parseInt( request.getParameter("9-9"));
//		int parametre910 =Integer.parseInt( request.getParameter("9-10"));
//		int parametre100 =Integer.parseInt( request.getParameter("10-0"));
//		int parametre101 =Integer.parseInt( request.getParameter("10-1"));
//		int parametre102 =Integer.parseInt( request.getParameter("10-2"));
//		int parametre103 =Integer.parseInt( request.getParameter("10-3"));
//		int parametre104 =Integer.parseInt( request.getParameter("10-4"));
//		int parametre105 =Integer.parseInt( request.getParameter("10-5"));
//		int parametre106 =Integer.parseInt( request.getParameter("10-6"));
//		int parametre107 =Integer.parseInt( request.getParameter("10-7"));
//		int parametre108 =Integer.parseInt( request.getParameter("10-8"));
//		int parametre109 =Integer.parseInt( request.getParameter("10-9"));
//		int parametre1010 =Integer.parseInt( request.getParameter("10-10"));
//		int parametre1100 =Integer.parseInt( request.getParameter("11-0"));
//		int parametre111 =Integer.parseInt( request.getParameter("11-1"));
//		int parametre112 =Integer.parseInt( request.getParameter("11-2"));
//		int parametre113 =Integer.parseInt( request.getParameter("11-3"));
//		int parametre114 =Integer.parseInt( request.getParameter("11-4"));
//		int parametre115 =Integer.parseInt( request.getParameter("11-5"));
//		int parametre116 =Integer.parseInt( request.getParameter("11-6"));
//		int parametre117 =Integer.parseInt( request.getParameter("11-7"));
//		int parametre118 =Integer.parseInt( request.getParameter("11-8"));
//		int parametre119 =Integer.parseInt( request.getParameter("11-9"));
//		int parametre1110 =Integer.parseInt( request.getParameter("11-10"));
//		int parametre120 =Integer.parseInt( request.getParameter("12-0"));
//		int parametre121 =Integer.parseInt( request.getParameter("12-1"));
//		int parametre122 =Integer.parseInt( request.getParameter("12-2"));
//		int parametre123 =Integer.parseInt( request.getParameter("12-3"));
//		int parametre124 =Integer.parseInt( request.getParameter("12-4"));
//		int parametre125 =Integer.parseInt( request.getParameter("12-5"));
//		int parametre126 =Integer.parseInt( request.getParameter("12-6"));
//		int parametre127 =Integer.parseInt( request.getParameter("12-7"));
//		int parametre128 =Integer.parseInt( request.getParameter("12-8"));
//		int parametre129 =Integer.parseInt( request.getParameter("12-9"));
//		int parametre1210 =Integer.parseInt( request.getParameter("12-10"));
//		int parametre130 =Integer.parseInt( request.getParameter("13-0"));
//		int parametre131 =Integer.parseInt( request.getParameter("13-1"));
//		int parametre132 =Integer.parseInt( request.getParameter("13-2"));
//		int parametre133 =Integer.parseInt( request.getParameter("13-3"));
//		int parametre134 =Integer.parseInt( request.getParameter("13-4"));
//		int parametre135 =Integer.parseInt( request.getParameter("13-5"));
//		int parametre136 =Integer.parseInt( request.getParameter("13-6"));
//		int parametre137 =Integer.parseInt( request.getParameter("13-7"));
//		int parametre138 =Integer.parseInt( request.getParameter("13-8"));
//		int parametre139 =Integer.parseInt( request.getParameter("13-9"));
//		int parametre1310 =Integer.parseInt( request.getParameter("13-10"));
//		int parametre140 =Integer.parseInt( request.getParameter("14-0"));
//		int parametre141 =Integer.parseInt( request.getParameter("14-1"));
//		int parametre142 =Integer.parseInt( request.getParameter("14-2"));
//		int parametre143 =Integer.parseInt( request.getParameter("14-3"));
//		int parametre144 =Integer.parseInt( request.getParameter("14-4"));
//		int parametre145 =Integer.parseInt( request.getParameter("14-5"));
//		int parametre146 =Integer.parseInt( request.getParameter("14-6"));
//		int parametre147 =Integer.parseInt( request.getParameter("14-7"));
//		int parametre148 =Integer.parseInt( request.getParameter("14-8"));
//		int parametre149 =Integer.parseInt( request.getParameter("14-9"));
//		int parametre1410 =Integer.parseInt( request.getParameter("14-10"));
//		int parametre150 =Integer.parseInt( request.getParameter("15-0"));
//		int parametre151 =Integer.parseInt( request.getParameter("15-1"));
//		int parametre152 =Integer.parseInt( request.getParameter("15-2"));
//		int parametre153 =Integer.parseInt( request.getParameter("15-3"));
//		int parametre154 =Integer.parseInt( request.getParameter("15-4"));
//		int parametre155 =Integer.parseInt( request.getParameter("15-5"));
//		int parametre156 =Integer.parseInt( request.getParameter("15-6"));
//		int parametre157 =Integer.parseInt( request.getParameter("15-7"));
//		int parametre158 =Integer.parseInt( request.getParameter("15-8"));
//		int parametre159 =Integer.parseInt( request.getParameter("15-9"));
//		int parametre1510 =Integer.parseInt( request.getParameter("15-10"));
//		int parametre160 =Integer.parseInt( request.getParameter("16-0"));
//		int parametre161 =Integer.parseInt( request.getParameter("16-1"));
//		int parametre162 =Integer.parseInt( request.getParameter("16-2"));
//		int parametre163 =Integer.parseInt( request.getParameter("16-3"));
//		int parametre164 =Integer.parseInt( request.getParameter("16-4"));
//		int parametre165 =Integer.parseInt( request.getParameter("16-5"));
//		int parametre166 =Integer.parseInt( request.getParameter("16-6"));
//		int parametre167 =Integer.parseInt( request.getParameter("16-7"));
//		int parametre168 =Integer.parseInt( request.getParameter("16-8"));
//		int parametre169 =Integer.parseInt( request.getParameter("16-9"));
//		int parametre1610 =Integer.parseInt( request.getParameter("16-10"));
//		int parametre170 =Integer.parseInt( request.getParameter("17-0"));
//		int parametre171 =Integer.parseInt( request.getParameter("17-1"));
//		int parametre172 =Integer.parseInt( request.getParameter("17-2"));
//		int parametre173 =Integer.parseInt( request.getParameter("17-3"));
//		int parametre174 =Integer.parseInt( request.getParameter("17-4"));
//		int parametre175 =Integer.parseInt( request.getParameter("17-5"));
//		int parametre176 =Integer.parseInt( request.getParameter("17-6"));
//		int parametre177 =Integer.parseInt( request.getParameter("17-7"));
//		int parametre178 =Integer.parseInt( request.getParameter("17-8"));
//		int parametre179 =Integer.parseInt( request.getParameter("17-9"));
//		int parametre1710 =Integer.parseInt( request.getParameter("17-10"));
//		int parametre180 =Integer.parseInt( request.getParameter("18-0"));
//		int parametre181 =Integer.parseInt( request.getParameter("18-1"));
//		int parametre182 =Integer.parseInt( request.getParameter("18-2"));
//		int parametre183 =Integer.parseInt( request.getParameter("18-3"));
//		int parametre184 =Integer.parseInt( request.getParameter("18-4"));
//		int parametre185 =Integer.parseInt( request.getParameter("18-5"));
//		int parametre186 =Integer.parseInt( request.getParameter("18-6"));
//		int parametre187 =Integer.parseInt( request.getParameter("18-7"));
//		int parametre188 =Integer.parseInt( request.getParameter("18-8"));
//		int parametre189 =Integer.parseInt( request.getParameter("18-9"));
//		int parametre1810 =Integer.parseInt( request.getParameter("18-10"));
		
		
		ArrayList<Integer> par = new ArrayList<Integer>();
		
		 par.add(parametre00);
		 par.add(parametre01);
//		 par.add(parametre02);
//		 par.add(parametre03);
//		 par.add(parametre04);
//		 par.add(parametre05);
//		 par.add(parametre06);
//		 par.add(parametre07);
//		 par.add(parametre08);
//		 par.add(parametre09);
//		 par.add(parametre010 );
//		 par.add(parametre10);
//		 par.add(parametre11);
//		 par.add(parametre12);
//		 par.add(parametre13);
//		 par.add(parametre14);
//		 par.add(parametre15);
//		 par.add(parametre16);
//		 par.add(parametre17);
//		 par.add(parametre18);
//		 par.add(parametre19);
//		 par.add(parametre110 );
//		 par.add(parametre20);
//		 par.add(parametre21);
//		 par.add(parametre22);
//		 par.add(parametre23);
//		 par.add(parametre24);
//		 par.add(parametre25);
//		 par.add(parametre26);
//		 par.add(parametre27);
//		 par.add(parametre28);
//		 par.add(parametre29);
//		 par.add(parametre210 );
//		 par.add(parametre30);
//		 par.add(parametre31);
//		 par.add(parametre32);
//		 par.add(parametre33);
//		 par.add(parametre34);
//		 par.add(parametre35);
//		 par.add(parametre36);
//		 par.add(parametre37);
//		 par.add(parametre38);
//		 par.add(parametre39);
//		 par.add(parametre310 );
//		 par.add(parametre40);
//		 par.add(parametre41);
//		 par.add(parametre42);
//		 par.add(parametre43);
//		 par.add(parametre44);
//		 par.add(parametre45);
//		 par.add(parametre46);
//		 par.add(parametre47);
//		 par.add(parametre48);
//		 par.add(parametre49);
//		 par.add(parametre410 );
//		 par.add(parametre50);
//		 par.add(parametre51);
//		 par.add(parametre52);
//		 par.add(parametre53);
//		 par.add(parametre54);
//		 par.add(parametre55);
//		 par.add(parametre56);
//		 par.add(parametre57);
//		 par.add(parametre58);
//		 par.add(parametre59);
//		 par.add(parametre510 );
//		 par.add(parametre60);
//		 par.add(parametre61);
//		 par.add(parametre62);
//		 par.add(parametre63);
//		 par.add(parametre64);
//		 par.add(parametre65);
//		 par.add(parametre66);
//		 par.add(parametre67);
//		 par.add(parametre68);
//		 par.add(parametre69);
//		 par.add(parametre610 );
//		 par.add(parametre70);
//		 par.add(parametre71);
//		 par.add(parametre72);
//		 par.add(parametre73);
//		 par.add(parametre74);
//		 par.add(parametre75);
//		 par.add(parametre76);
//		 par.add(parametre77);
//		 par.add(parametre78);
//		 par.add(parametre79);
//		 par.add(parametre710 );
//		 par.add(parametre80);
//		 par.add(parametre81);
//		 par.add(parametre82);
//		 par.add(parametre83);
//		 par.add(parametre84);
//		 par.add(parametre85);
//		 par.add(parametre86);
//		 par.add(parametre87);
//		 par.add(parametre88);
//		 par.add(parametre89);
//		 par.add(parametre810 );
//		 par.add(parametre90);
//		 par.add(parametre91);
//		 par.add(parametre92);
//		 par.add(parametre93);
//		 par.add(parametre94);
//		 par.add(parametre95);
//		 par.add(parametre96);
//		 par.add(parametre97);
//		 par.add(parametre98);
//		 par.add(parametre99);
//		 par.add(parametre910 );
//		 par.add(parametre100 );
//		 par.add(parametre101 );
//		 par.add(parametre102 );
//		 par.add(parametre103 );
//		 par.add(parametre104 );
//		 par.add(parametre105 );
//		 par.add(parametre106 );
//		 par.add(parametre107 );
//		 par.add(parametre108 );
//		 par.add(parametre109 );
//		 par.add(parametre1010);
//		 par.add(parametre1100);
//		 par.add(parametre111 );
//		 par.add(parametre112 );
//		 par.add(parametre113 );
//		 par.add(parametre114 );
//		 par.add(parametre115 );
//		 par.add(parametre116 );
//		 par.add(parametre117 );
//		 par.add(parametre118 );
//		 par.add(parametre119 );
//		 par.add(parametre1110);
//		 par.add(parametre120 );
//		 par.add(parametre121 );
//		 par.add(parametre122 );
//		 par.add(parametre123 );
//		 par.add(parametre124 );
//		 par.add(parametre125 );
//		 par.add(parametre126 );
//		 par.add(parametre127 );
//		 par.add(parametre128 );
//		 par.add(parametre129 );
//		 par.add(parametre1210);
//		 par.add(parametre130 );
//		 par.add(parametre131 );
//		 par.add(parametre132 );
//		 par.add(parametre133 );
//		 par.add(parametre134 );
//		 par.add(parametre135 );
//		 par.add(parametre136 );
//		 par.add(parametre137 );
//		 par.add(parametre138 );
//		 par.add(parametre139 );
//		 par.add(parametre1310);
//		 par.add(parametre140 );
//		 par.add(parametre141 );
//		 par.add(parametre142 );
//		 par.add(parametre143 );
//		 par.add(parametre144 );
//		 par.add(parametre145 );
//		 par.add(parametre146 );
//		 par.add(parametre147 );
//		 par.add(parametre148 );
//		 par.add(parametre149 );
//		 par.add(parametre1410);
//		 par.add(parametre150 );
//		 par.add(parametre151 );
//		 par.add(parametre152 );
//		 par.add(parametre153 );
//		 par.add(parametre154 );
//		 par.add(parametre155 );
//		 par.add(parametre156 );
//		 par.add(parametre157 );
//		 par.add(parametre158 );
//		 par.add(parametre159 );
//		 par.add(parametre1510);
//		 par.add(parametre160 );
//		 par.add(parametre161 );
//		 par.add(parametre162 );
//		 par.add(parametre163 );
//		 par.add(parametre164 );
//		 par.add(parametre165 );
//		 par.add(parametre166 );
//		 par.add(parametre167 );
//		 par.add(parametre168 );
//		 par.add(parametre169 );
//		 par.add(parametre1610);
//		 par.add(parametre170 );
//		 par.add(parametre171 );
//		 par.add(parametre172 );
//		 par.add(parametre173 );
//		 par.add(parametre174 );
//		 par.add(parametre175 );
//		 par.add(parametre176 );
//		 par.add(parametre177 );
//		 par.add(parametre178 );
//		 par.add(parametre179 );
//		 par.add(parametre1710);
//		 par.add(parametre180 );
//		 par.add(parametre181 );
//		 par.add(parametre182 );
//		 par.add(parametre183 );
//		 par.add(parametre184 );
//		 par.add(parametre185 );
//		 par.add(parametre186 );
//		 par.add(parametre187 );
//		 par.add(parametre188 );
//		 par.add(parametre189 );
//		 par.add(parametre1810);
		
		 int overall = 0;
		 
		for (int i = 0; i <par.size() ; i++) {
			  overall=overall+overall;
			}
		sesion.setAttribute("overall",overall);
		
		
//		sesion.setAttribute("0-0", parametre00);
//		sesion.setAttribute("0-1", parametre01);
//		sesion.setAttribute("0-2", parametre02);
//		sesion.setAttribute("0-3", parametre03);
//		sesion.setAttribute("0-4", parametre04);
//		sesion.setAttribute("0-5", parametre05);
//		sesion.setAttribute("0-6", parametre06);
//		sesion.setAttribute("0-7", parametre07);
//		sesion.setAttribute("0-8", parametre08);
//		sesion.setAttribute("0-9", parametre09);
//		sesion.setAttribute("0-10", parametre010);
//		sesion.setAttribute("1-0", parametre10);
//		sesion.setAttribute("1-1", parametre11);
//		sesion.setAttribute("1-2", parametre12);
//		sesion.setAttribute("1-3", parametre13);
//		sesion.setAttribute("1-4", parametre14);
//		sesion.setAttribute("1-5", parametre15);
//		sesion.setAttribute("1-6", parametre16);
//		sesion.setAttribute("1-7", parametre17);
//		sesion.setAttribute("1-8", parametre18);
//		sesion.setAttribute("1-9", parametre19);
//		sesion.setAttribute("1-10", parametre110);
//		sesion.setAttribute("2-0", parametre20);
//		sesion.setAttribute("2-1", parametre21);
//		sesion.setAttribute("2-2", parametre22);
//		sesion.setAttribute("2-3", parametre23);
//		sesion.setAttribute("2-4", parametre24);
//		sesion.setAttribute("2-5", parametre25);
//		sesion.setAttribute("2-6", parametre26);
//		sesion.setAttribute("2-7", parametre27);
//		sesion.setAttribute("2-8", parametre28);
//		sesion.setAttribute("2-9", parametre29);
//		sesion.setAttribute("2-10", parametre210);
//		sesion.setAttribute("3-0", parametre30);
//		sesion.setAttribute("3-1", parametre31);
//		sesion.setAttribute("3-2", parametre32);
//		sesion.setAttribute("3-3", parametre33);
//		sesion.setAttribute("3-4", parametre34);
//		sesion.setAttribute("3-5", parametre35);
//		sesion.setAttribute("3-6", parametre36);
//		sesion.setAttribute("3-7", parametre37);
//		sesion.setAttribute("3-8", parametre38);
//		sesion.setAttribute("3-9", parametre39);
//		sesion.setAttribute("3-10", parametre310);
//		sesion.setAttribute("4-0", parametre40);
//		sesion.setAttribute("4-1", parametre41);
//		sesion.setAttribute("4-2", parametre42);
//		sesion.setAttribute("4-3", parametre43);
//		sesion.setAttribute("4-4", parametre44);
//		sesion.setAttribute("4-5", parametre45);
//		sesion.setAttribute("4-6", parametre46);
//		sesion.setAttribute("4-7", parametre47);
//		sesion.setAttribute("4-8", parametre48);
//		sesion.setAttribute("4-9", parametre49);
//		sesion.setAttribute("4-10", parametre410);
//		sesion.setAttribute("5-0", parametre50);
//		sesion.setAttribute("5-1", parametre51);
//		sesion.setAttribute("5-2", parametre52);
//		sesion.setAttribute("5-3", parametre53);
//		sesion.setAttribute("5-4", parametre54);
//		sesion.setAttribute("5-5", parametre55);
//		sesion.setAttribute("5-6", parametre56);
//		sesion.setAttribute("5-7", parametre57);
//		sesion.setAttribute("5-8", parametre58);
//		sesion.setAttribute("5-9", parametre59);
//		sesion.setAttribute("5-10", parametre510);
//		sesion.setAttribute("6-0", parametre60);
//		sesion.setAttribute("6-1", parametre61);
//		sesion.setAttribute("6-2", parametre62);
//		sesion.setAttribute("6-3", parametre63);
//		sesion.setAttribute("6-4", parametre64);
//		sesion.setAttribute("6-5", parametre65);
//		sesion.setAttribute("6-6", parametre66);
//		sesion.setAttribute("6-7", parametre67);
//		sesion.setAttribute("6-8", parametre68);
//		sesion.setAttribute("6-9", parametre69);
//		sesion.setAttribute("6-10", parametre610);
//		sesion.setAttribute("7-0", parametre70);
//		sesion.setAttribute("7-1", parametre71);
//		sesion.setAttribute("7-2", parametre72);
//		sesion.setAttribute("7-3", parametre73);
//		sesion.setAttribute("7-4", parametre74);
//		sesion.setAttribute("7-5", parametre75);
//		sesion.setAttribute("7-6", parametre76);
//		sesion.setAttribute("7-7", parametre77);
//		sesion.setAttribute("7-8", parametre78);
//		sesion.setAttribute("7-9", parametre79);
//		sesion.setAttribute("7-10", parametre710);
//		sesion.setAttribute("8-0", parametre80);
//		sesion.setAttribute("8-1", parametre81);
//		sesion.setAttribute("8-2", parametre82);
//		sesion.setAttribute("8-3", parametre83);
//		sesion.setAttribute("8-4", parametre84);
//		sesion.setAttribute("8-5", parametre85);
//		sesion.setAttribute("8-6", parametre86);
//		sesion.setAttribute("8-7", parametre87);
//		sesion.setAttribute("8-8", parametre88);
//		sesion.setAttribute("8-9", parametre89);
//		sesion.setAttribute("8-10", parametre810);
//		sesion.setAttribute("9-0", parametre90);
//		sesion.setAttribute("9-1", parametre91);
//		sesion.setAttribute("9-2", parametre92);
//		sesion.setAttribute("9-3", parametre93);
//		sesion.setAttribute("9-4", parametre94);
//		sesion.setAttribute("9-5", parametre95);
//		sesion.setAttribute("9-6", parametre96);
//		sesion.setAttribute("9-7", parametre97);
//		sesion.setAttribute("9-8", parametre98);
//		sesion.setAttribute("9-9", parametre99);
//		sesion.setAttribute("9-10", parametre910);
//		sesion.setAttribute("10-0", parametre100);
//		sesion.setAttribute("10-1", parametre101);
//		sesion.setAttribute("10-2", parametre102);
//		sesion.setAttribute("10-3", parametre103);
//		sesion.setAttribute("10-4", parametre104);
//		sesion.setAttribute("10-5", parametre105);
//		sesion.setAttribute("10-6", parametre106);
//		sesion.setAttribute("10-7", parametre107);
//		sesion.setAttribute("10-8", parametre108);
//		sesion.setAttribute("10-9", parametre109);
//		sesion.setAttribute("10-10", parametre1010);
//		sesion.setAttribute("11-0", parametre1100);
//		sesion.setAttribute("11-1", parametre111);
//		sesion.setAttribute("11-2", parametre112);
//		sesion.setAttribute("11-3", parametre113);
//		sesion.setAttribute("11-4", parametre114);
//		sesion.setAttribute("11-5", parametre115);
//		sesion.setAttribute("11-6", parametre116);
//		sesion.setAttribute("11-7", parametre117);
//		sesion.setAttribute("11-8", parametre118);
//		sesion.setAttribute("11-9", parametre119);
//		sesion.setAttribute("11-10", parametre1110);
//		sesion.setAttribute("12-0", parametre120);
//		sesion.setAttribute("12-1", parametre121);
//		sesion.setAttribute("12-2", parametre122);
//		sesion.setAttribute("12-3", parametre123);
//		sesion.setAttribute("12-4", parametre124);
//		sesion.setAttribute("12-5", parametre125);
//		sesion.setAttribute("12-6", parametre126);
//		sesion.setAttribute("12-7", parametre127);
//		sesion.setAttribute("12-8", parametre128);
//		sesion.setAttribute("12-9", parametre129);
//		sesion.setAttribute("12-10", parametre1210);
//		sesion.setAttribute("13-0", parametre130);
//		sesion.setAttribute("13-1", parametre131);
//		sesion.setAttribute("13-2", parametre132);
//		sesion.setAttribute("13-3", parametre133);
//		sesion.setAttribute("13-4", parametre134);
//		sesion.setAttribute("13-5", parametre135);
//		sesion.setAttribute("13-6", parametre136);
//		sesion.setAttribute("13-7", parametre137);
//		sesion.setAttribute("13-8", parametre138);
//		sesion.setAttribute("13-9", parametre139);
//		sesion.setAttribute("13-10", parametre1310);
//		sesion.setAttribute("14-0", parametre140);
//		sesion.setAttribute("14-1", parametre141);
//		sesion.setAttribute("14-2", parametre142);
//		sesion.setAttribute("14-3", parametre143);
//		sesion.setAttribute("14-4", parametre144);
//		sesion.setAttribute("14-5", parametre145);
//		sesion.setAttribute("14-6", parametre146);
//		sesion.setAttribute("14-7", parametre147);
//		sesion.setAttribute("14-8", parametre148);
//		sesion.setAttribute("14-9", parametre149);
//		sesion.setAttribute("14-10", parametre1410);
//		sesion.setAttribute("15-0", parametre150);
//		sesion.setAttribute("15-1", parametre151);
//		sesion.setAttribute("15-2", parametre152);
//		sesion.setAttribute("15-3", parametre153);
//		sesion.setAttribute("15-4", parametre154);
//		sesion.setAttribute("15-5", parametre155);
//		sesion.setAttribute("15-6", parametre156);
//		sesion.setAttribute("15-7", parametre157);
//		sesion.setAttribute("15-8", parametre158);
//		sesion.setAttribute("15-9", parametre159);
//		sesion.setAttribute("15-10", parametre1510);
//		sesion.setAttribute("16-0", parametre160);
//		sesion.setAttribute("16-1", parametre161);
//		sesion.setAttribute("16-2", parametre162);
//		sesion.setAttribute("16-3", parametre163);
//		sesion.setAttribute("16-4", parametre164);
//		sesion.setAttribute("16-5", parametre165);
//		sesion.setAttribute("16-6", parametre166);
//		sesion.setAttribute("16-7", parametre167);
//		sesion.setAttribute("16-8", parametre168);
//		sesion.setAttribute("16-9", parametre169);
//		sesion.setAttribute("16-10", parametre1610);
//		sesion.setAttribute("17-0", parametre170);
//		sesion.setAttribute("17-1", parametre171);
//		sesion.setAttribute("17-2", parametre172);
//		sesion.setAttribute("17-3", parametre173);
//		sesion.setAttribute("17-4", parametre174);
//		sesion.setAttribute("17-5", parametre175);
//		sesion.setAttribute("17-6", parametre176);
//		sesion.setAttribute("17-7", parametre177);
//		sesion.setAttribute("17-8", parametre178);
//		sesion.setAttribute("17-9", parametre179);
//		sesion.setAttribute("17-10", parametre1710);
//		sesion.setAttribute("18-0", parametre180);
//		sesion.setAttribute("18-1", parametre181);
//		sesion.setAttribute("18-2", parametre182);
//		sesion.setAttribute("18-3", parametre183);
//		sesion.setAttribute("18-4", parametre184);
//		sesion.setAttribute("18-5", parametre185);
//		sesion.setAttribute("18-6", parametre186);
//		sesion.setAttribute("18-7", parametre187);
//		sesion.setAttribute("18-8", parametre188);
//		sesion.setAttribute("18-9", parametre189);
//		sesion.setAttribute("18-10", parametre1810);
		System.out.println(parametre00);
		System.out.println(overall);
		response.sendRedirect("substep22.jsp");
		//stock all that stuff in DB
	}

}
